apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: firefusion-runtime-secrets
  namespace: firefusion

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "firefusion/BROKER_URL"
        objectType: "secretsmanager"

      - objectName: "firefusion/CACHE_URL"
        objectType: "secretsmanager"

      - objectName: "firefusion/DB_URL"
        objectType: "secretsmanager"

      - objectName: "firefusion/RELATIONAL_DB_URL"
        objectType: "secretsmanager"

      - objectName: "firefusion/API_KEY"
        objectType: "secretsmanager"

      - objectName: "firefusion/VALID_API_KEY"
        objectType: "secretsmanager"

  secretObjects:
    - secretName: firefusion-runtime-secrets
      type: Opaque
      data:
        - objectName: "firefusion/BROKER_URL"
          key: BROKER_URL
        - objectName: "firefusion/CACHE_URL"
          key: CACHE_URL
        - objectName: "firefusion/DB_URL"
          key: DB_URL
        - objectName: "firefusion/RELATIONAL_DB_URL"
          key: RELATIONAL_DB_URL
        - objectName: "firefusion/API_KEY"
          key: API_KEY
        - objectName: "firefusion/VALID_API_KEY"
          key: VALID_API_KEY
