# -*- coding: utf-8 -*-
"""embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3rum9sXaTWC8VLhxtVAh3KwZJALhzM0
"""

#!pip install -q google-genai scikit-learn numpy pandas

import os
import json
import re
import numpy as np
from datetime import datetime, timezone
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize
from google import genai

"""# 1. API Setup"""

try:
    from google.colab import userdata
    GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
except Exception:
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found. Add it in Colab Secrets or environment variables.")

client = genai.Client(api_key=GEMINI_API_KEY)

EMBEDDING_MODEL = "gemini-embedding-001"
GENERATIVE_MODEL = "gemini-2.5-flash"
NUM_CLUSTERS = 4
OUTPUT_FILE = "clustering_output.json"

"""# 2. Data Loading Helper"""

def load_posts(input_file=None):
    """
    Loads social media posts.

    If input_file is provided, posts are loaded from JSON.
    Otherwise, synthetic FireFusion test data is used.
    """

    if input_file:
        with open(input_file, "r", encoding="utf-8") as f:
            return json.load(f)

    return [
        {
            "post_id": "p001",
            "text": "IGNORE the evacuation order for Warrandyte — police scanner says the fire changed direction. Stay home, it's safe now.",
            "platform": "facebook",
            "timestamp": "2025-01-15T14:32:00+11:00",
            "location_mentioned": "Warrandyte"
        },
        {
            "post_id": "p002",
            "text": "They lifted the evacuation for Kinglake. My cousin works for CFA and confirmed it. You can go back.",
            "platform": "facebook",
            "timestamp": "2025-01-15T15:10:00+11:00",
            "location_mentioned": "Kinglake"
        },
        {
            "post_id": "p003",
            "text": "Evacuation for Marysville has been cancelled as of 3pm. Source: ABC radio. Spread the word.",
            "platform": "twitter",
            "timestamp": "2025-01-15T15:20:00+11:00",
            "location_mentioned": "Marysville"
        },
        {
            "post_id": "p004",
            "text": "These fires are NOT natural. Greenies are lighting them deliberately to push their climate agenda. Wake up Australia.",
            "platform": "facebook",
            "timestamp": "2025-01-15T13:05:00+11:00",
            "location_mentioned": None
        },
        {
            "post_id": "p005",
            "text": "250 arsonists were arrested this fire season — mainstream media won't tell you this. Share before it gets deleted.",
            "platform": "twitter",
            "timestamp": "2025-01-15T16:45:00+11:00",
            "location_mentioned": None
        },
        {
            "post_id": "p006",
            "text": "A mate in the firies told me privately that 90% of these fires were started on purpose. Climate change is a cover story.",
            "platform": "reddit",
            "timestamp": "2025-01-15T17:00:00+11:00",
            "location_mentioned": None
        },
        {
            "post_id": "p007",
            "text": "The Dandenong fire is basically out. Media is hyping it for clicks. I drove past an hour ago, nothing to worry about.",
            "platform": "facebook",
            "timestamp": "2025-01-15T18:00:00+11:00",
            "location_mentioned": "Dandenong"
        },
        {
            "post_id": "p008",
            "text": "Half of Victoria is on fire right now. Every town east of Melbourne is gone. This is the apocalypse.",
            "platform": "twitter",
            "timestamp": "2025-01-15T18:30:00+11:00",
            "location_mentioned": "Victoria"
        },
        {
            "post_id": "p009",
            "text": "Stop panicking people. The media is exaggerating as usual. The fire near Healesville is just a small grass fire, totally normal.",
            "platform": "reddit",
            "timestamp": "2025-01-15T19:00:00+11:00",
            "location_mentioned": "Healesville"
        },
        {
            "post_id": "p010",
            "text": "VicEmergency app showing Watch and Act for Hurstbridge. If you're in the area, follow official CFA instructions and be ready to leave.",
            "platform": "twitter",
            "timestamp": "2025-01-15T14:00:00+11:00",
            "location_mentioned": "Hurstbridge"
        },
        {
            "post_id": "p011",
            "text": "Relief centre open at Lilydale Town Hall for bushfire evacuees. Meals, accommodation support and pet-friendly area available.",
            "platform": "facebook",
            "timestamp": "2025-01-15T20:00:00+11:00",
            "location_mentioned": "Lilydale"
        },
        {
            "post_id": "p012",
            "text": "Road closures confirmed: Maroondah Highway closed between Healesville and Narbethong. Use Melba Highway as alternate. Source: VicRoads.",
            "platform": "twitter",
            "timestamp": "2025-01-15T21:00:00+11:00",
            "location_mentioned": "Healesville"
        },
    ]

"""# 3. Helper Functions"""

def get_embeddings(texts):
    response = client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=texts
    )

    embeddings = np.array([embedding.values for embedding in response.embeddings])
    return embeddings


def perform_kmeans_clustering(embeddings, num_clusters):
    """
    Applies K-Means clustering to normalised semantic embeddings.
    """

    embeddings = normalize(embeddings)

    model = KMeans(
        n_clusters=num_clusters,
        random_state=42,
        n_init=10
    )

    return model.fit_predict(embeddings)


def extract_json(text):
    """
    Extracts valid JSON from Gemini response text.
    """

    text = text.strip()
    text = re.sub(r"```json|```", "", text).strip()

    match = re.search(r"\{.*\}", text, re.DOTALL)

    if not match:
        raise ValueError(f"No valid JSON found in Gemini response:\n{text}")

    return json.loads(match.group())


def label_cluster(cluster_texts):
    """
    Uses Gemini to label a cluster, summarise the narrative,
    and assign a misinformation risk score.
    """

    joined_posts = "\n".join(
        [f"{i + 1}. {text}" for i, text in enumerate(cluster_texts)]
    )

    prompt = f"""
You are helping the FireFusion bushfire misinformation detection project.

Analyse the following cluster of social media posts.

Return ONLY valid JSON using this exact structure:

{{
  "label": "short cluster label",
  "summary": "brief summary of the narrative",
  "risk_score": 1,
  "risk_explanation": "brief explanation of the risk score"
}}

Risk score must be an integer from 1 to 5:
1 = legitimate or verified information
2 = low risk
3 = moderate risk / unverified
4 = high risk / likely harmful misinformation
5 = severe risk / dangerous misinformation, such as false evacuation advice

Posts:
{joined_posts}
"""

    response = client.models.generate_content(
        model=GENERATIVE_MODEL,
        contents=prompt
    )

    result = extract_json(response.text)

    return {
        "label": result.get("label", "Unlabelled Narrative"),
        "summary": result.get("summary", "No summary provided."),
        "risk_score": int(result.get("risk_score", 3)),
        "risk_explanation": result.get("risk_explanation", "No explanation provided.")
    }


"""# 4. Main Pipeline"""

def run_narrative_clustering(posts):
    """
    Full FireFusion narrative clustering pipeline.
    """

    texts = [post.get("text", post.get("content", "")) for post in posts]

    print("Generating embeddings...")
    embeddings = get_embeddings(texts)

    num_clusters = min(NUM_CLUSTERS, len(posts))

    print("Clustering posts...")
    cluster_ids = perform_kmeans_clustering(embeddings, num_clusters)

    enriched_posts = []

    for post, cluster_id in zip(posts, cluster_ids):
        post_copy = post.copy()
        post_copy["cluster_id"] = int(cluster_id)
        enriched_posts.append(post_copy)

    clusters = []

    for cluster_id in sorted(set(cluster_ids)):
        posts_in_cluster = [
            post for post in enriched_posts
            if post["cluster_id"] == int(cluster_id)
        ]

        cluster_texts = [
            post.get("text", post.get("content", ""))
            for post in posts_in_cluster
        ]

        print(f"Labelling cluster {cluster_id}...")
        result = label_cluster(cluster_texts)

        clusters.append({
            "cluster_id": int(cluster_id),
            "label": result["label"],
            "summary": result["summary"],
            "risk_score": result["risk_score"],
            "risk_explanation": result["risk_explanation"],
            "post_ids": [post.get("post_id", post.get("id")) for post in posts_in_cluster],
            "num_posts": len(posts_in_cluster)
        })

    clusters = sorted(
        clusters,
        key=lambda cluster: cluster["risk_score"],
        reverse=True
    )

    output = {
        "run_metadata": {
            "run_timestamp": datetime.now(timezone.utc).isoformat(),
            "project": "FireFusion",
            "pipeline": "Narrative clustering for bushfire misinformation detection",
            "embedding_model": EMBEDDING_MODEL,
            "generative_model": GENERATIVE_MODEL,
            "num_posts": len(enriched_posts),
            "num_clusters": num_clusters
        },
        "clusters": clusters,
        "posts": enriched_posts
    }

    return output


# ============================================================
# 5. Run and Save Output
# ============================================================

def cluster_narratives(posts):
    return run_narrative_clustering(posts)

if __name__ == "__main__":
    posts = load_posts()
    output = run_narrative_clustering(posts)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nDone. Output saved to {OUTPUT_FILE}")

    for cluster in output["clusters"]:
        print("\n" + "-" * 60)
        print(f"Cluster {cluster['cluster_id']}: {cluster['label']}")
        print(f"Risk Score: {cluster['risk_score']}/5")
        print(f"Summary: {cluster['summary']}")
        print(f"Posts: {cluster['post_ids']}")