apiVersion: v1
kind: Secret
metadata:
  name: firefusion-runtime-secrets
  namespace: firefusion
  labels:
    app.kubernetes.io/name: firefusion-runtime-secrets
    app.kubernetes.io/part-of: firefusion-platform
type: Opaque

stringData:
  BROKER_URL: "REPLACE_WITH_BROKER_CONNECTION_STRING"
  DB_URL: "REPLACE_WITH_DATABASE_CONNECTION_STRING"
  RELATIONAL_DB_URL: "REPLACE_WITH_DATABASE_CONNECTION_STRING"
  API_KEY: "REPLACE_WITH_API_KEY"
  VALID_API_KEY: "REPLACE_WITH_MODEL_API_KEY"
