apiVersion: v1
kind: ServiceAccount
metadata:
  name: firefusion-backend
  namespace: firefusion
  labels:
    app.kubernetes.io/name: firefusion-backend
    app.kubernetes.io/part-of: firefusion-platform
automountServiceAccountToken: false
