apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: firefusion-runtime-secrets
  namespace: firefusion

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
    keyvaultName: "REPLACE_WITH_KEY_VAULT_NAME"
    tenantId: "REPLACE_WITH_AZURE_TENANT_ID"

    objects: |
      array:
        - |
          objectName: BROKER-URL
          objectType: secret
        - |
          objectName: CACHE-URL
          objectType: secret
        - |
          objectName: DB-URL
          objectType: secret
        - |
          objectName: RELATIONAL-DB-URL
          objectType: secret
        - |
          objectName: API-KEY
          objectType: secret
        - |
          objectName: VALID-API-KEY
          objectType: secret

  secretObjects:
    - secretName: firefusion-runtime-secrets
      type: Opaque
      data:
        - objectName: BROKER-URL
          key: BROKER_URL
        - objectName: CACHE-URL
          key: CACHE_URL
        - objectName: DB-URL
          key: DB_URL
        - objectName: RELATIONAL-DB-URL
          key: RELATIONAL_DB_URL
        - objectName: API-KEY
          key: API_KEY
        - objectName: VALID-API-KEY
          key: VALID_API_KEY
