apiVersion: v1
kind: ServiceAccount
metadata:
  name: firefusion-backend
  namespace: firefusion
  annotations:
    iam.gke.io/gcp-service-account: "REPLACE_WITH_SERVICE_ACCOUNT@REPLACE_WITH_PROJECT_ID.iam.gserviceaccount.com"
