apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: firefusion-runtime-secrets
  namespace: firefusion

spec:
  provider: gcp

  parameters:
    secrets: |
      - resourceName: "projects/REPLACE_WITH_PROJECT_ID/secrets/BROKER_URL/versions/latest"
        path: "BROKER_URL"

      - resourceName: "projects/REPLACE_WITH_PROJECT_ID/secrets/CACHE_URL/versions/latest"
        path: "CACHE_URL"

      - resourceName: "projects/REPLACE_WITH_PROJECT_ID/secrets/DB_URL/versions/latest"
        path: "DB_URL"

      - resourceName: "projects/REPLACE_WITH_PROJECT_ID/secrets/RELATIONAL_DB_URL/versions/latest"
        path: "RELATIONAL_DB_URL"

      - resourceName: "projects/REPLACE_WITH_PROJECT_ID/secrets/API_KEY/versions/latest"
        path: "API_KEY"

      - resourceName: "projects/REPLACE_WITH_PROJECT_ID/secrets/VALID_API_KEY/versions/latest"
        path: "VALID_API_KEY"

  secretObjects:
    - secretName: firefusion-runtime-secrets
      type: Opaque
      data:
        - objectName: BROKER_URL
          key: BROKER_URL
        - objectName: CACHE_URL
          key: CACHE_URL
        - objectName: DB_URL
          key: DB_URL
        - objectName: RELATIONAL_DB_URL
          key: RELATIONAL_DB_URL
        - objectName: API_KEY
          key: API_KEY
        - objectName: VALID_API_KEY
          key: VALID_API_KEY
